import type { ReactNode } from "react";

import { Header, Footer, Theme } from "@/components";
import { i18n } from "@/i18n-config";
import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params,
}: {
  children: ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={params.lang}>
      <Theme>
        <body className="min-h-screen flex flex-col max-w-full mx-auto xl:max-w-7xl">
          <Header />
          <main className="flex-1 flex flex-col">{children}</main>
          <Footer />
        </body>
      </Theme>
    </html>
  );
}
